

export const actionTypes = {
    GET_ERRORS : "GET_ERRORS",
    USER_LOADING : "USER_LOADING",
    SET_CURRENT_USER : "SET_CURRENT_USER",
    USER_LOADED: "USER_LOADED",
    AUTH_ERROR: "AUTH_ERROR",
    LOGIN_SUCCES: " LOGIN_SUCCES",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT_SUCCES: "LOGOUT_SUCCES",
    REGISTER_SUCCES: "REGISTER_SUCCES",
    REGISTER_FAIL :  "REGISTER_FAIL",
    GET_ERRORS: "GET_ERRORS",
    CLEAR_ERRORS: "CLEAR_ERRORS",
}

 